<Project Sdk="Meziantou.NET.Sdk.Test">

  <PropertyGroup>
    <TargetFramework>net$(NETCoreAppMaximumVersion)</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Meziantou.Framework.InlineSnapshotTesting" Version="6.0.1" />
    <PackageReference Include="Meziantou.Framework.TemporaryDirectory" Version="3.0.1" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Meziantou.FileMover\Meziantou.FileMover.csproj" />
  </ItemGroup>

</Project>
